language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          compiler: gcc
          sudo: required
        - os: osx
          osx_image: xcode9.3
          compiler: gcc
        - os: osx
          osx_image: xcode9.3
          compiler: clang

before_install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew update
            brew install premake
            brew install clang-format
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            sudo apt-get -qq update -y
            sudo apt-get install premake4 -y
            sudo apt-get install clang-format -y
            sudo ln -s /usr/bin/make /usr/bin/gmake
        fi

script:
    - |
        valid=true
        for filename in 'source/sepia.hpp' 'test/sepia.cpp'; do
            formatted_filename="$(dirname $filename)/formatted_$(basename $filename)"
            clang-format $filename > $formatted_filename
            if [ "$(diff $filename $formatted_filename)" != '' ]; then
                printf "'$filename' is not properly formatted, run \`clang-format -i '$filename'\`\n"
                valid=false
            fi
            rm $formatted_filename
        done
        if [ "$valid" = false ]; then
            false
        fi
    - git submodule update --init --recursive
    - premake4 gmake
    - cd build
    - make
    - cd release
    - ./sepia
